mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.index),
    path('products/', views.ProductListView.as_view(),name='products'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/add/', views.CreateProductView.as_view(), name='add_product'),
    path('products/update/<int:pk>/', views.UpdateProductView.as_view(), name='update_product'),
    path('products/delete/<int:pk>/', views.DeleteProductView.as_view(), name='delete_product'),
    path('products/mylistings/', views.my_listings, name='my_listings'),

]   

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/',include('myapp.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as authentication_views
app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/', views.profile,name='profile'),
    path('create_profile/', views.create_profile,name='create_profile'),
    path('seller_profile/<int:id>/', views.seller_profile,name='seller_profile'),
]   

mysite/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Product(models.Model):
    
    seller_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=200)
    image = models.ImageField(blank=True, upload_to = 'images')
    
    def get_absolute_url(self):
        return reverse('myapp:products')
    def __str__(self):
        return self.name

mysite/users/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(to=User, on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg', upload_to='profile_pictures')
    contact_number = models.CharField(max_length=20, default='999999')

    def __str__(self):
        return self.user.username

mysite/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs = {'class':'focus:outline-none', 'placeholder': 'demo@gmail.com'}))
    username = forms.CharField(required=True,widget=forms.TextInput(attrs = {'class':'focus:outline-none', 'placeholder': 'user123'}))
    password1 =  forms.CharField(required=True,widget=forms.PasswordInput(attrs = {'class':'focus:outline-none'}))
    password2 =  forms.CharField(required=True,widget=forms.PasswordInput(attrs = {'class':'focus:outline-none'}))

    class Meta:
        model = User
        fields = ("username","email","password1","password2")
        
    def save(self,commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

mysite/myapp/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import Product
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.core.paginator import Paginator
def index(request):
    return HttpResponse('hello there')

# def products(request):
#     page_obj = products = Product.objects.all()

#     product_name = request.GET.get('product_name')
#     if product_name != '' and product_name is not None:
#         page_obj = products.filter(name__icontains = product_name)
        

#     paginator = Paginator(page_obj,3)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     context = {
#         'page_obj':page_obj
#     }
#     return render(request,'myapp/index.html',context)


# def product_detail(request,id):
#     product = Product.objects.get(id=id)
#     context = {
#         'product':product
#     }
#     return render(request,'myapp/detail.html',context)

# @login_required
# def add_product(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         price = request.POST.get('price')
#         desc = request.POST.get('desc')
#         image = request.FILES['upload']
#         seller_name=request.user
#         product = Product(name=name, price=price, desc=desc, image=image,seller_name=seller_name)
#         product.save()

#     return render(request,'myapp/addproduct.html')
# def update_product(request,id):
#     product = Product.objects.get(id=id)

#     if request.method == 'POST':
#         product.name = request.POST.get('name')
#         product.price = request.POST.get('price')
#         product.desc = request.POST.get('desc')
#         product.image = request.FILES['upload']

#         product.save()
#         return redirect('/myapp/products')

#     context = {
#         'product':product
#     }

#     return render(request, 'myapp/update_product.html',context)
    

# def delete_product(request,id):
# product = Product.objects.get(id=id)
# context = {
#     'product':product
# }

# if request.method == 'POST':
#     product.delete()
#     return redirect('/myapp/products')


# return render(request, 'myapp/delete_product.html',context)
# Class Based View [ListView]
class ProductListView(ListView):
    model = Product
    template_name = 'myapp/index.html'
    context_object_name = 'products'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            object_list = self.model.objects.filter(name__icontains=query)
        else:
            object_list = self.model.objects.all()
        return object_list


class ProductDetailView(DetailView):
    model = Product
    template_name = 'myapp/detail.html'
    context_object_name = 'product'

class CreateProductView(CreateView):
    model = Product
    fields = ['name', 'price','desc', 'image', 'seller_name']

class UpdateProductView(UpdateView):
    model = Product
    fields = ['name', 'price','desc', 'image', 'seller_name']
    template_name_suffix = '_update_form'

class DeleteProductView(DeleteView):
    model = Product
    success_url = reverse_lazy('myapp:products')


@login_required
def my_listings(request):
    products = Product.objects.filter(seller_name=request.user)
    context = {
        'products':products, 
    }
    return render(request, 'myapp/my_listings.html',context)

mysite/users/views.py
from django.shortcuts import redirect, render
from .forms import NewUserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Profile

def register(request):
    if request.method =='POST':
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect('myapp/products')

    form = NewUserForm()
    context = {
        'form':form,
    }
    return render(request,'users/register.html',context)

@login_required
def profile(request):
    return render(request, 'users/profile.html')


def create_profile(request):
    if request.method == 'POST':
        contact = request.POST.get('contact')
        image = request.FILES['upload']
        user = request.user   
        profile = Profile(user=user, image=image, contact_number = contact)
        profile.save()

    return render(request, 'users/create_profile.html')

def seller_profile(request,id):
    seller = User.objects.get(id=id)
    context = {
        'seller':seller,
    }
    return render(request, 'users/seller_profile.html',context=context)

mysite/myapp/templates/myapp/addproduct.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-2xl m-10 font-bold">+ Add Product</h1>
<form class="w-3/5 bg-white rounded-xl shadow-lg m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="iPhone" type="text" name="name" id="name">
    </div>

    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="price">Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="800" type="number" name="price" id="price">
    </div>

    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="desc">Description</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="This is an iPhone" type="text" name="desc" id="desc">
    </div>

    <div class="mb-7">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="upload">Upload File</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <button class="bg-blue-600 text-white px-5 py-2 text-bolder rounded-md mb-10 " type="submit" name="Add Product" value="Add Product">Add Product</button>
</form>
{% endblock %}

mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
    <title>Index</title>
</head>

<body>
    <nav class="bg-white shadow-lg ">
        <div class="sm:w-full  md:w-full mx-auto py-4">
            <div class="flex justify-between">
                <div class="flex space-x-7">
                    <div>
                        <a class="flex items-center px-2 py-4" href="{% url 'myapp:products' %}">
                            <img class="h-8 w-8" src="{% static 'myapp/images/shopping.png' %}" alt="">
                            <span class="text-gray-500 text-lg font-semibold">Buy&Sell</span>
                        </a>
                    </div>
                    <div class="flex items-center space-x-10">
                        <a href="{% url 'myapp:products' %}" 
                            class="py-4 text-gray-500 font-semibold border-b-4 border-green-500">
                            Home
                        </a>
                        <a href="{% url 'myapp:add_product' %}" 
                            class="py-4 text-gray-500 font-semibold">
                            Post Ad
                        </a>
                        <a href="{% url 'myapp:products' %}" 
                            class="py-4 text-gray-500 font-semibold">
                            View Products
                        </a>
                        {% if user.is_authenticated %}
                        <a class="py-4 ml-5 mr-5 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                        <a class="py-4 text-gray-500 font-semibold" href="{% url 'myapp:my_listings' %}">My Listings</a>
                        <a class="py-4 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                        <a class="py-4 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
</body>

</html>

mysite/myapp/templates/myapp/delete_product.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-2xl m-10 font-bold">Delete Product</h1>
<form class="w-3/5 bg-white rounded-xl shadow-lg m-10 px-8 py-8" method="POST">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="iPhone"
            value="{{product.name}}" type="text" name="name" id="name">
    </div>

    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="price">Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="800"
            value="{{product.price}}" type="number" name="price" id="price">
    </div>

    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="desc">Description</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{product.desc}}"
            placeholder="This is an iPhone" type="text" name="desc" id="desc">
    </div>

    <div class="mb-7">
        <img class="w-20 h-20" src="{{product.image.url}}" alt="{{product.name}}">
    </div>
    <button 
        class="bg-red-600 text-white px-5 py-2 text-bolder rounded-md mb-10" 
        type="submit" 
        name="delete"
        id = "delete"
        value="Delete Product">
        Delete Product
    </button>
    <a class="button bg-green-600 text-white px-5 py-2 text-bolder rounded-md mb-10"
        href="{% url 'myapp:products' %}">Cancel
    </a>
</form>
{% endblock %}

mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="flex p-10 w-full h-200">
  <img class="w-1/3 h-100 w-50 " src="{{product.image.url}}" alt="{{product.name}}">
  <div class="w-2/3 text-xl ml-10">
    <div class="mt-5">{{ product.name }}</div>
    <div class="mt-5 text-green-500">$ {{ product.price }}</div>
    <div class="mt-5 text-gray-700">{{ product.desc }}</div>
    <div class="mt-5 text-gray-700">Posted By : <a href="{% url 'users:seller_profile' product.seller_name.id %}">{{ product.seller_name }}</a></div>
    <div class="mt-5 text-gray-700">Contact : {{ product.seller_name.profile.contact_number }}</div>
  </div>
</div>
{% endblock %}

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block content %}
<!-- Site Hero starts here -->
<main class="mt-10 mx-auto max-w-7xl px-4 sm:st-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
  <div class="sm: text-center lg:text-left">
    <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
      <span class="block xl: inline">Premium Products</span>
      <span class="block text-green-500 xl:inline">Non-Premium Prices</span>
    </h1>
    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx-auto md:mt-5 md:text-xl lg:mx-0">Get the
      best quality used products across the globe, Free Shipping</p>
  </div>
</main>

<!-- Site Hero ends here -->

<div class="flex mt-5 p-10 justify-center">
  <h2 class="text-3xl font-normal mt-0 mb-2 text-gray-500">Recent Products</h2>
</div>

<div class="mt-5 p-10 justify-center">
  <h2>Search Product</h2>
  <form method="GET">
    <input class="font-bold text-lg text-gray-700" 
            type="text" 
            name="q" 
            id="q"
            placeholder="Product 1">
  </form>
</div>


<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md: grid-cols-3 xl: grid-cols-3 lg:grid-cols-3 gap-5">
  <!-- Card -->
  {% for product in page_obj %}
  <a href="{% url 'myapp:product_detail' product.id  %}">
    <div class="rounded overflow-hidden shadow-lg">
      <img class="w-50 h-100 mx-auto" src="{{ product.image.url }}" alt="{{product.name}}">
      <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2">{{ product.name }}</div>
        <div class="font-bold text-xl text-green-500 mb-2">$ {{ product.price }}</div>
        <div class="font-bold mb-2">Posted By : <span class="text-indigo-500">{{ product.seller_name }}</span></div>
        <p class="text-gray-700 text-base"> {{ product.desc }} </p>
      </div>
    </div>
  </a>

  {% endfor %}
</div>
<!-- pagination -->
<div class="pagination flex justify-center items-center mb-20">
  <span>
    {% if page_obj.has_previous %}
    <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"
      href="?page=1">First</a>
    <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"
      href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    <span
      class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10">
      Page {{page_obj.number}} of {{ page_obj.paginator.num_pages }}
    </span>
    <span>
      {% if page_obj.has_next %}
      <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"
        href="?page={{ page_obj.next_page_number }}">Next</a>
      <a class="text-sm font-medium border py-2 px-4 items-center inline-flex relative text-green-500 border-green-500 z10"
        href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
    </span>
  </span>
</div>
{% endblock %}

mysite/myapp/templates/myapp/my_listings.html
{% extends 'myapp/base.html' %}

{% block content %}

<div class="text-2xl m-10 p-10 font-bold">📃 My Listings</div>

{% for product in products %}
<div class="itemcontainer flex shadow-lg m-10 p-10">
    <span class="w-1/5">
        <img class="w-40 h-40" src="{{product.image.url}}" alt="">
    </span>
    <span class="w-2/5">
        <div class="font-bold text-gray-700">{{ product.name }}</div>
        <div class="font-bold text-green-500">$ {{ product.price }}</div>
        <div>{{ product.desc }}</div>
    </span>
    <span class="w-1/5 my-10 mx-10">
        <a class="bg-green-500 text-white font-bold px-5 py-2 rounded-md"
            href="{% url 'myapp:update_product' product.id %}">
            Edit
        </a>
    </span>
    <span class="w-1/5 my-10 mx-10">
        <a class="bg-red-500 text-white font-bold px-5 py-2 rounded-md"
            href="{% url 'myapp:delete_product' product.id %}">
            Delete
        </a>
    </span>
</div>

{% endfor %}

{% endblock %}

mysite/myapp/templates/myapp/product_confirm_delete.html
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"</p>
    {{form}}
    <input type="submit" value="Confirm"> 

</form>

mysite/myapp/templates/myapp/product_form.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-2xl m-10 font-bold">+ Add Product</h1>
<form class="w-3/5 bg-white rounded-xl shadow-lg m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name</label>
        <div class="w-1/3 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700">
            {{form.name}}
        </div>
    </div>

    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="price">Price</label>
        <div class="w-1/3 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700">
            {{form.price}}
        </div>
    </div>

    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="desc">Description</label>
        <div class="w-1/3 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700">
            {{form.desc}}
        </div>
    </div>

    <div class="mb-7">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="upload">Upload File</label>
        <div class="w-1/3 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700">
            {{form.image}}
        </div>
    </div>

    <div class="mb-4">
        <div class="hidden w-1/3 shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700">
            {{form.seller_name}}
        </div>
    </div>
    <button class="bg-blue-600 text-white px-5 py-2 text-bolder rounded-md mb-10 " type="submit" name="Add Product"
        value="Add Product">Add Product</button>
</form>

{% endblock %}

mysite/myapp/templates/myapp/product_update_form.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="Update" value="Update">
</form>

mysite/myapp/templates/myapp/update_product.html
{% extends 'myapp/base.html' %}

{% block content %}

<h1 class="text-2xl m-10 font-bold">Update Product</h1>
<form class="w-3/5 bg-white rounded-xl shadow-lg m-10 px-8 py-8" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="name">Name</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="iPhone"
            value="{{product.name}}" type="text" name="name" id="name">
    </div>

    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="price">Price</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" placeholder="800"
           value="{{product.price}}" type="number" name="price" id="price">
    </div>

    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="desc">Description</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700"
           value="{{product.desc}}" placeholder="This is an iPhone" type="text" name="desc" id="desc">
    </div>

    <div class="mb-7">
        <img class="w-20 h-20" src="{{product.image.url}}" alt="{{product.name}}">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="upload">Upload File</label>
        <input class="py-2" type="file" accept="image/*" name="upload" id="upload">
    </div>
    <button class="bg-blue-600 text-white px-5 py-2 text-bolder rounded-md mb-10 " type="submit" name="Edit Product"
        value="Edit Product">Edit Product</button>
</form>
{% endblock %}

mysite/users/templates/users/create_profile.html
{% extends 'myapp/base.html' %}
{% block content %}
<form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block font-bold text-gray text-sm" for="upload">Upload Profile Image</label>
        <input class="py-2" type="file" name="upload" id="upload" accept="image/*" placeholder="Upload a Clear Profile Image">
    </div>
    <div class="mb-4">
        <label class="block font-bold text-gray text-sm" for="contact">Input Contact Number</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" name="contact" id="contact" accept="image/*" placeholder="08123456789">
    </div>
    <input class="bg-green-500 text-white px-5 py-2 rounded-md" name="submit" type="submit" value="Submit">
</form>
{% endblock %}

mysite/users/templates/users/login.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl ml-10 mt-10 font-bold">👱‍♂️ Login User</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="POST">
        {% csrf_token %}

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.username}}
            </div>
        </div>

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.password}}
            </div>
        </div>

        <button class="bg-green-600 text-white px-5 py-2 text-bolder rounded-md mt-8 mb-10 " type="submit">
            Login</button>
    </form>
    <div class="m-10">Do not have an account ?
        <a class="text-indigo-500" href="{% url 'users:register' %}">Register</a>
    </div>

</div>
{% endblock %}

mysite/users/templates/users/logout.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1>
    you have been logged out

</h1>
{% endblock %}

mysite/users/templates/users/profile.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div class="p-5">
            <img class="w-1/2 h-1/2" src="{{user.profile.image.url}}" alt="">
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4"> {{ user.username }} </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">📞 {{ user.profile.contact_number }}</div>
    </div>
</div>
{% endblock %}

mysite/users/templates/users/register.html
{% extends 'myapp/base.html' %}
{% block content %}
<h1 class="text-2xl ml-10 mt-10 font-bold">👱‍♂️ Register User</h1>
<div class="container py-5">
    <form class="w-2/5 bg-white shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="POST">
        {% csrf_token %}

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Username</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.username}}
            </div>
        </div>

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Email</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.email}}
            </div>
        </div>

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Password</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.password1}}
            </div>
        </div>

        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Confirm Paswword</label>
            <div class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">
                {{form.password2}}
            </div>
        </div>
        <button class="bg-green-600 text-white px-5 py-2 text-bolder rounded-md mt-8 mb-10 " type="submit">
            Register</button>
    </form>
    <div class="m-10">Already have an account ?
        <a class="text-indigo-500" href="{% url 'users:login' %}">Login</a>
    </div>

</div>
{% endblock %}

mysite/users/templates/users/seller_profile.html
{% extends 'myapp/base.html' %}
{% block content %}

<div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadow-lg">
        <div class="p-5">
            <img class="w-1/2 h-1/2" src="{{seller.profile.image.url}}" alt="">
        </div>
        <div class="font-bold text-xl mb-2 px-6 py-4"> {{ user.username }} </div>
        <div class="font-bold text-xl mb-2 px-6 py-4">📞 {{ user.profile.contact_number }}</div>
    </div>
</div>
{% endblock %}